<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefTarifTransportDaratSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('ref_tarif_transport_darat')->insert([
            // Banda Aceh
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Barat', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Barat Daya', 'besaran' => 298000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Besar', 'besaran' => 183000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Jaya', 'besaran' => 238000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Selatan', 'besaran' => 325000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Singkil', 'besaran' => 420000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Tamiang', 'besaran' => 315000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Tengah', 'besaran' => 293000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Tenggara', 'besaran' => 460000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Timur', 'besaran' => 289000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Aceh Utara', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Bener Meriah', 'besaran' => 278000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Bireuen', 'besaran' => 220000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Gayo Lues', 'besaran' => 370000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Nagan Raya', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Pidie', 'besaran' => 190000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kab. Pidie Jaya', 'besaran' => 205000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kota Langsa', 'besaran' => 301000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kota Lhokseumawe', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Banda Aceh', 'kabupaten_kota_tujuan' => 'Kota Subulussalam', 'besaran' => 400000],

            // Medan
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Asahan', 'besaran' => 259000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Batubara', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Dairi', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Deli Serdang', 'besaran' => 186000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Humbang Hasundutan', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Karo', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Labuhan Batu', 'besaran' => 287000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Labuhan Batu Selatan', 'besaran' => 360000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Labuhan Batu Utara', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Langkat', 'besaran' => 186000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Mandailing Natal', 'besaran' => 420000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Padang Lawas', 'besaran' => 420000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Padang Lawas Utara', 'besaran' => 420000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Pakpak Bharat', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Samosir', 'besaran' => 330000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Serdang Bedagai', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Simalungun', 'besaran' => 264000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Tapanuli Selatan', 'besaran' => 328000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Tapanuli Tengah', 'besaran' => 345000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Tapanuli Utara', 'besaran' => 330000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kab. Toba Samosir', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kota Binjai', 'besaran' => 180000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kota Pematang Siantar', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kota Sibolga', 'besaran' => 345000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kota Tanjung Balai', 'besaran' => 285000],
            ['ibukota_provinsi' => 'Medan', 'kabupaten_kota_tujuan' => 'Kota Tebing Tinggi', 'besaran' => 203000],

            // Pekanbaru
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Indragiri Hilir', 'besaran' => 380000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Indragiri Hulu', 'besaran' => 315000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Kampar', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Kuantan Singingi', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Pelalawan', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Rokan Hilir', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Rokan Hulu', 'besaran' => 322000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kab. Siak', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Pekanbaru', 'kabupaten_kota_tujuan' => 'Kota Dumai', 'besaran' => 400000],

            // Tanjung Pinang
            ['ibukota_provinsi' => 'Tanjung Pinang', 'kabupaten_kota_tujuan' => 'Kab. Bintan', 'besaran' => 185000],

            // Jambi
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Batanghari', 'besaran' => 175000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Bungo', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Kerinci', 'besaran' => 325000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Merangin', 'besaran' => 260000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Muaro Jambi', 'besaran' => 170000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Sarolangun', 'besaran' => 241000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Tanjung Jabung Barat', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Tanjung Jabung Timur', 'besaran' => 190000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kab. Tebo', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Jambi', 'kabupaten_kota_tujuan' => 'Kota Sungai Penuh', 'besaran' => 308000],

            // Padang
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Agam', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Dharmasraya', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Lima Puluh Kota', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Padang Pariaman', 'besaran' => 205000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Pasaman', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Pasaman Barat', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Pesisir Selatan', 'besaran' => 205000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Sijunjung', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Solok', 'besaran' => 210000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Solok Selatan', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kab. Tanah Datar', 'besaran' => 220000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kota Bukit Tinggi', 'besaran' => 215000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kota Padang Panjang', 'besaran' => 210000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kota Pariaman', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kota Payakumbuh', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kota Sawahlunto', 'besaran' => 215000],
            ['ibukota_provinsi' => 'Padang', 'kabupaten_kota_tujuan' => 'Kota Solok', 'besaran' => 210000],

            // Palembang
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Banyuasin', 'besaran' => 203000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Empat Lawang', 'besaran' => 315000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Lahat', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Muara Enim', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Musi Banyuasin', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Musi Rawas', 'besaran' => 320000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Musi Rawas Utara', 'besaran' => 325000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Ogan Ilir', 'besaran' => 205000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Ogan Komering Ilir', 'besaran' => 205000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Ogan Komering Ulu', 'besaran' => 248000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Ogan Komering Ulu Selatan', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Ogan Komering Ulu Timur', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kab. Pali', 'besaran' => 265000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kota Lubuk Linggau', 'besaran' => 290000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kota Pagar Alam', 'besaran' => 280000],
            ['ibukota_provinsi' => 'Palembang', 'kabupaten_kota_tujuan' => 'Kota Prabumulih', 'besaran' => 205000],

            // Bandar Lampung
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Lampung Barat', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Lampung Selatan', 'besaran' => 234000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Lampung Tengah', 'besaran' => 246000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Lampung Timur', 'besaran' => 246000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Lampung Utara', 'besaran' => 252000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Mesuji', 'besaran' => 276000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Pesawaran', 'besaran' => 216000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Pesisir Barat', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Pringsewu', 'besaran' => 222000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Tanggamus', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Tulang Bawang', 'besaran' => 252000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Tulang Bawang Barat', 'besaran' => 267000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kab. Way Kanan', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Bandar Lampung', 'kabupaten_kota_tujuan' => 'Kota Metro', 'besaran' => 234000],

            // Bengkulu
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Bengkulu Selatan', 'besaran' => 344000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Bengkulu Tengah', 'besaran' => 232000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Bengkulu Utara', 'besaran' => 313000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Kaur', 'besaran' => 385000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Kepahiang', 'besaran' => 298000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Lebong', 'besaran' => 375000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Mukomuko', 'besaran' => 423000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Rejang Lebong', 'besaran' => 313000],
            ['ibukota_provinsi' => 'Bengkulu', 'kabupaten_kota_tujuan' => 'Kab. Seluma', 'besaran' => 282000],

            // Pangkalpinang
            ['ibukota_provinsi' => 'Pangkalpinang', 'kabupaten_kota_tujuan' => 'Kab. Bangka', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Pangkalpinang', 'kabupaten_kota_tujuan' => 'Kab. Bangka Barat', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Pangkalpinang', 'kabupaten_kota_tujuan' => 'Kab. Bangka Selatan', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Pangkalpinang', 'kabupaten_kota_tujuan' => 'Kab. Bangka Tengah', 'besaran' => 250000],

            // Serang
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kab. Lebak', 'besaran' => 208000],
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kab. Pandeglang', 'besaran' => 138000],
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kab. Serang', 'besaran' => 160000],
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kab. Tangerang', 'besaran' => 254000],
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kota Cilegon', 'besaran' => 160000],
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kota Tangerang', 'besaran' => 313000],
            ['ibukota_provinsi' => 'Serang', 'kabupaten_kota_tujuan' => 'Kota Tangerang Selatan', 'besaran' => 347000],

            // Bandung
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Bandung', 'besaran' => 183000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Bandung Barat', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Bekasi', 'besaran' => 265000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Bogor', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Ciamis', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Cianjur', 'besaran' => 215000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Cirebon', 'besaran' => 280000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Garut', 'besaran' => 243000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Indramayu', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Karawang', 'besaran' => 248000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Kuningan', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Majalengka', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Pangadaran', 'besaran' => 283000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Purwakarta', 'besaran' => 218000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Subang', 'besaran' => 208000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Sukabumi', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Sumedang', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kab. Tasikmalaya', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Banjar', 'besaran' => 283000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Bekasi', 'besaran' => 265000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Bogor', 'besaran' => 285000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Cimahi', 'besaran' => 168000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Cirebon', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Depok', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Sukabumi', 'besaran' => 226000],
            ['ibukota_provinsi' => 'Bandung', 'kabupaten_kota_tujuan' => 'Kota Tasikmalaya', 'besaran' => 245000],

            // Semarang
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Banjarnegara', 'besaran' => 260000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Banyumas', 'besaran' => 257000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Batang', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Blora', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Boyolali', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Brebes', 'besaran' => 263000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Cilacap', 'besaran' => 280000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Demak', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Grobogan', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Jepara', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Karanganyar', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Kebumen', 'besaran' => 260000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Kendal', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Klaten', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Kudus', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Magelang', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Pati', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Pekalongan', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Pemalang', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Purbalingga', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Purworejo', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Rembang', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Semarang', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Sragen', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Sukoharjo', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Tegal', 'besaran' => 260000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Temanggung', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Wonogiri', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kab. Wonosobo', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kota Magelang', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kota Pekalongan', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kota Salatiga', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kota Surakarta', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Semarang', 'kabupaten_kota_tujuan' => 'Kota Tegal', 'besaran' => 260000],

            // Yogyakarta
            ['ibukota_provinsi' => 'Yogyakarta', 'kabupaten_kota_tujuan' => 'Kab. Bantul', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Yogyakarta', 'kabupaten_kota_tujuan' => 'Kab. Gunung Kidul', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Yogyakarta', 'kabupaten_kota_tujuan' => 'Kab. Kulon Progo', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Yogyakarta', 'kabupaten_kota_tujuan' => 'Kab. Sleman', 'besaran' => 200000],

            // Surabaya
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Bangkalan', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Banyuwangi', 'besaran' => 285000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Blitar', 'besaran' => 255000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Bojonegoro', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Bondowoso', 'besaran' => 255000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Gresik', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Jember', 'besaran' => 261000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Jombang', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Kediri', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Lamongan', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Lumajang', 'besaran' => 261000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Madiun', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Magetan', 'besaran' => 253000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Malang', 'besaran' => 228000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Mojokerto', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Nganjuk', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Ngawi', 'besaran' => 253000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Pacitan', 'besaran' => 285000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Pamekasan', 'besaran' => 243000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Pasuruan', 'besaran' => 228000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Ponorogo', 'besaran' => 255000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Probolinggo', 'besaran' => 228000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Sampang', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Sidoarjo', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Situbondo', 'besaran' => 255000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Sumenep', 'besaran' => 255000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Trenggalek', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Tuban', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kab. Tulungagung', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Batu', 'besaran' => 242000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Blitar', 'besaran' => 255000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Bojonegoro', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Kediri', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Madiun', 'besaran' => 245000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Malang', 'besaran' => 228000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Mojokerto', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Surabaya', 'kabupaten_kota_tujuan' => 'Kota Probolinggo', 'besaran' => 228000],

            // Denpasar
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Badung', 'besaran' => 188000],
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Bangli', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Buleleng', 'besaran' => 265000],
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Gianyar', 'besaran' => 225000],
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Jembrana', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Karangasem', 'besaran' => 263000],
            ['ibukota_provinsi' => 'Denpasar', 'kabupaten_kota_tujuan' => 'Kab. Tabanan', 'besaran' => 225000],

            // Mataram
            ['ibukota_provinsi' => 'Mataram', 'kabupaten_kota_tujuan' => 'Kab. Lombok Barat', 'besaran' => 325000],
            ['ibukota_provinsi' => 'Mataram', 'kabupaten_kota_tujuan' => 'Kab. Lombok Tengah', 'besaran' => 450000],
            ['ibukota_provinsi' => 'Mataram', 'kabupaten_kota_tujuan' => 'Kab. Lombok Timur', 'besaran' => 350000],

            // Kupang
            ['ibukota_provinsi' => 'Kupang', 'kabupaten_kota_tujuan' => 'Kab. Belu', 'besaran' => 325000],
            ['ibukota_provinsi' => 'Kupang', 'kabupaten_kota_tujuan' => 'Kab. Kupang', 'besaran' => 175000],
            ['ibukota_provinsi' => 'Kupang', 'kabupaten_kota_tujuan' => 'Kab. Timor Tengah Selatan', 'besaran' => 218000],
            ['ibukota_provinsi' => 'Kupang', 'kabupaten_kota_tujuan' => 'Kab. Timor Tengah Utara', 'besaran' => 275000],

            // Pontianak
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Bengkayang', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Kapuas Hulu', 'besaran' => 550000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Kayong Utara', 'besaran' => 550000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Ketapang', 'besaran' => 550000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Kubu Raya', 'besaran' => 185000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Landak', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Melawi', 'besaran' => 430000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Mempawah', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Sambas', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Sanggau', 'besaran' => 303000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Sekadau', 'besaran' => 343000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kab. Sintang', 'besaran' => 392000],
            ['ibukota_provinsi' => 'Pontianak', 'kabupaten_kota_tujuan' => 'Kota Singkawang', 'besaran' => 257000],

            // Palangkaraya
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Barito Selatan', 'besaran' => 290000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Barito Timur', 'besaran' => 333000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Barito Utara', 'besaran' => 425000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Gunung Mas', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Kapuas', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Katingan', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Kotawaringin Barat', 'besaran' => 425000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Kotawaringin Timur', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Lamandau', 'besaran' => 525000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Murung Raya', 'besaran' => 448000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Pulau Pisau', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Seruyan', 'besaran' => 328000],
            ['ibukota_provinsi' => 'Palangkaraya', 'kabupaten_kota_tujuan' => 'Kab. Sukamara', 'besaran' => 525000],

            // Banjarmasin
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Balangan', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Banjar', 'besaran' => 170000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Barito Kuala', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Hulu Sungai Selatan', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Hulu Sungai Tengah', 'besaran' => 212000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Hulu Sungai Utara', 'besaran' => 218000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Kota Baru', 'besaran' => 290000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Tabalong', 'besaran' => 234000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Tanah Bumbu', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Tanah Laut', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kab. Tapin', 'besaran' => 189000],
            ['ibukota_provinsi' => 'Banjarmasin', 'kabupaten_kota_tujuan' => 'Kota Banjarbaru', 'besaran' => 225000],

            // Samarinda
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kab. Kutai Barat', 'besaran' => 1500000],
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kab. Kutai Kartanegara', 'besaran' => 500000],
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kab. Kutai Timur', 'besaran' => 1350000],
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kab. Paser', 'besaran' => 1650000],
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kab. Penajam Paser Utara', 'besaran' => 650000],
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kota Balikpapan', 'besaran' => 550000],
            ['ibukota_provinsi' => 'Samarinda', 'kabupaten_kota_tujuan' => 'Kota Bontang', 'besaran' => 600000],

            // Manado
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Bolaang Mongondow', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Bolaang Mongondow Selatan', 'besaran' => 275000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Bolaang Mongondow Timur', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Bolaang Mongondow Utara', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Minahasa', 'besaran' => 180000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Minahasa Selatan', 'besaran' => 180000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Minahasa Tenggara', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kab. Minahasa Utara', 'besaran' => 175000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kota Bitung', 'besaran' => 175000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kota Kotamobagu', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Manado', 'kabupaten_kota_tujuan' => 'Kota Tomohon', 'besaran' => 170000],

            // Gorontalo
            ['ibukota_provinsi' => 'Gorontalo', 'kabupaten_kota_tujuan' => 'Kab. Boalemo', 'besaran' => 400000],
            ['ibukota_provinsi' => 'Gorontalo', 'kabupaten_kota_tujuan' => 'Kab. Gorontalo', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Gorontalo', 'kabupaten_kota_tujuan' => 'Kab. Gorontalo Utara', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Gorontalo', 'kabupaten_kota_tujuan' => 'Kab. Pahuwato', 'besaran' => 650000],

            // Mamuju
            ['ibukota_provinsi' => 'Mamuju', 'kabupaten_kota_tujuan' => 'Kab. Majene', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Mamuju', 'kabupaten_kota_tujuan' => 'Kab. Mamasa', 'besaran' => 359000],
            ['ibukota_provinsi' => 'Mamuju', 'kabupaten_kota_tujuan' => 'Kab. Mamuju Tengah', 'besaran' => 200000],
            ['ibukota_provinsi' => 'Mamuju', 'kabupaten_kota_tujuan' => 'Kab. Mamuju utara', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Mamuju', 'kabupaten_kota_tujuan' => 'Kab. Polewali Mandar', 'besaran' => 260000],

            // Makassar
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Bantaeng', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Barru', 'besaran' => 210000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Bone', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Bulukumba', 'besaran' => 240000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Enrekang', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Gowa', 'besaran' => 175000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Jeneponto', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Luwu', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Luwu Timur', 'besaran' => 375000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Luwu Utara', 'besaran' => 365000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Maros', 'besaran' => 170000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Pinrang', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Sidenreng Rappang', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Sinjai', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Soppeng', 'besaran' => 235000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Takalar', 'besaran' => 190000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Tanatoraja', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Toraja Utara', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kab. Wajo', 'besaran' => 230000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kota Palopo', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Makassar', 'kabupaten_kota_tujuan' => 'Kota Pare-Pare', 'besaran' => 225000],

            // Palu
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Luwuk', 'besaran' => 400000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Buol', 'besaran' => 472000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Donggala', 'besaran' => 130000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Morowali', 'besaran' => 400000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Morowali Utara', 'besaran' => 400000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Parigi Moutong', 'besaran' => 250000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Poso', 'besaran' => 280000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Sigi', 'besaran' => 219000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Tojouna-Una', 'besaran' => 350000],
            ['ibukota_provinsi' => 'Palu', 'kabupaten_kota_tujuan' => 'Kab. Toli-Toli', 'besaran' => 412000],

            // Kendari
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Bombana', 'besaran' => 355000],
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Kolaka', 'besaran' => 370000],
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Kolaka Timur', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Kolaka Utara', 'besaran' => 425000],
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Konawe', 'besaran' => 300000],
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Konawe Selatan', 'besaran' => 305000],
            ['ibukota_provinsi' => 'Kendari', 'kabupaten_kota_tujuan' => 'Kab. Konawe Utara', 'besaran' => 300000],

            // Sofifi
            ['ibukota_provinsi' => 'Sofifi', 'kabupaten_kota_tujuan' => 'Kab. Halmahera Barat', 'besaran' => 850000],
            ['ibukota_provinsi' => 'Sofifi', 'kabupaten_kota_tujuan' => 'Kab. Halmahera Tengah', 'besaran' => 1000000],
            ['ibukota_provinsi' => 'Sofifi', 'kabupaten_kota_tujuan' => 'Kab. Halmahera Timur', 'besaran' => 1250000],
            ['ibukota_provinsi' => 'Sofifi', 'kabupaten_kota_tujuan' => 'Kab. Halmahera Utara', 'besaran' => 900000],

            // Jayapura
            ['ibukota_provinsi' => 'Jayapura', 'kabupaten_kota_tujuan' => 'Kab. Jayapura', 'besaran' => 600000],
            ['ibukota_provinsi' => 'Jayapura', 'kabupaten_kota_tujuan' => 'Kab. Keerom', 'besaran' => 900000],
            ['ibukota_provinsi' => 'Jayapura', 'kabupaten_kota_tujuan' => 'Kab. Sarmi', 'besaran' => 2700000],

            // Manokwari
            ['ibukota_provinsi' => 'Manokwari', 'kabupaten_kota_tujuan' => 'Kab. Teluk Bintuni', 'besaran' => 900000],
            ['ibukota_provinsi' => 'Manokwari', 'kabupaten_kota_tujuan' => 'Kab. Manokwari Selatan', 'besaran' => 750000],
            ['ibukota_provinsi' => 'Manokwari', 'kabupaten_kota_tujuan' => 'Kab. Pegunungan Arfak', 'besaran' => 265000],

            // Jakarta
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kota Bekasi', 'besaran' => 256000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kab. Bekasi', 'besaran' => 256000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kab. Bogor', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kota Bogor', 'besaran' => 270000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kota Depok', 'besaran' => 248000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kota Tangerang', 'besaran' => 258000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kota Tangerang Selatan', 'besaran' => 258000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kab. Tangerang', 'besaran' => 279000],
            ['ibukota_provinsi' => 'Jakarta', 'kabupaten_kota_tujuan' => 'Kepulauan Seribu', 'besaran' => 386000],
        ]);
    }
}
