name: Node.js Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run build script
      - name: Run build script
        run: npm run build

      # 5. Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: my-build-files
          path: public/build # Ganti ke 'dist' jika ini proyek Vue/React murni
